quarkus.hibernate-orm.database.generation=update
%dev.quarkus.hibernate-orm.sql-load-script=seed.sql

# Tipo de base de datos
quarkus.datasource.db-kind=postgresql

# URL JDBC
quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-d9cjmgf41pts739iv4vg-a.oregon-postgres.render.com:5432/medico_9zap

# Credenciales
quarkus.datasource.username=medico_9zap_user
quarkus.datasource.password=u4JKarmIlDo9iUFHixJBy3Y5VXQrGmaV

# Configuración SSL (Requerida por Render)

quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET, OPTIONS, HEAD, PUT, POST

quarkus.datasource.jdbc.driver=org.postgresql.Driver
smallrye.jwt.encrypt.key.location=publicKey.pem
quarkus.http.port=8081