quarkus.hibernate-orm.database.generation=update
%dev.quarkus.hibernate-orm.sql-load-script=seed.sql

# Tipo de base de datos
quarkus.datasource.db-kind=postgresql

# URL JDBC
quarkus.datasource.jdbc.url=jdbc:postgresql://pg-3d50d49d-dbaa.g.aivencloud.com:10642/defaultdb?ssl=require&user=avnadmin&password=AVNS_yB8V-l3P2qWHhnFpnUL
# Credenciales
quarkus.datasource.username=medico_9zap_user
quarkus.datasource.password=u4JKarmIlDo9iUFHixJBy3Y5VXQrGmaV

# Configuración SSL (Requerida por Render)

quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET, OPTIONS, HEAD, PUT, POST

quarkus.datasource.jdbc.driver=org.postgresql.Driver
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.issuer=quarkus-jwt
quarkus.http.port=8081
quarkus.http.auth.basic=false
quarkus.swagger-ui.always-include=true 